### ISSUE TITLE
JOSS review: Documentation

### ISSUE THREAD

**Issue by tkoskela** [henry2004y/Vlasiator.jl#121]
- [x] I think the [documentation](https://henry2004y.github.io/Vlasiator.jl/stable/benchmark/) should include instructions on how to reproduce the results. I've ran `benchmarks.jl` using `PkgBenchmarks` but it's not entirely clear to me how the results relate to what is reported in the documentation. The files `perf.jl` and `perf.py` probably should not be included in the package as they contain hard-coded file and path names that aren't part of the package.
- [x] The paper comments on how good the interoperability is with other community packages. I'm curious why you have chosen to define your own physical constants, instead of using a community package, such as [PhysicalConstants.jl](https://github.com/JuliaPhysics/PhysicalConstants.jl)
- [x] The link to [repo](https://github.com/henry2004y/Vlasiator.jl/tree/master/src/examples) in https://github.com/henry2004y/Vlasiator.jl/blob/feda666f96ed87fb2928221680b2b5cd5473106b/docs/src/manual.md?plain=1#L233 is broken

https://github.com/openjournals/joss-reviews/issues/4906

**Comment by henry2004y** [comment]
Thanks for the review!

1. The link is fixed.
2. PhysicalConstants.jl is a nice collection of constants, but it come naturally with the dependencies on Unitful.jl which is something we haven't tested carefully. Having predefined units is good, but it unavoidably comes at a cost of performance. Also, in order to make computations convenient and consistent, we may have to define my own unit system for commonly used units in our community, which is also not fully tested. Thus we decided to define the constants inside the package (which is currently only ~ 10 lines). Currently based on this [list](https://juliahub.com/ui/Packages/PhysicalConstants/ykpMf/0.2.3?page=2), a few of the astrophysics packages depend on it.  In the future, we may make a switch if PhysicalConstants.jl proves to be a nice addition.
3. About the benchmarks between Julia and Python, the most tricky part, as the reviewers also pointed out in #122 and #115, is that VLSV format files generated from Vlasiator are either large or non-public. In order to show the comparisons at real work situations, our current solution is to run `perf.jl` and `perf.py` on private data on the server with different sizes. The [test data](https://henry2004y.github.io/Vlasiator.jl/stable/log/#Test-Data) for this package contains 3 VLSV files which are intently kept small. If we use those for the benchmarks, then only reading DCCRG grid variables at very small array sizes can be shown, which may not be ideal. Our current plan is to update `perf.jl` and `perf.py` and make better descriptions to the benchmark results.

**Comment by tkoskela** [comment]
Apologies, I had not looked under `Log` for instructions on how to run the benchmarks. I think renaming it to FAQ makes it a bit more obvious, but I would also put a link to it from the Benchmarks page. Probably that's part of your plans in making better descriptions of the benchmark results.

I understand that the size of the data files may prevent you from distributing them as part of the package. I don't really have an universal solution for that, I would suggest looking at services your institute or HPC center may offer for data storage and distribution. I'm perhaps a bit confused about the issue of data being non-public. If there is no public data, it's difficult to see the benefits of an open source processing tool. I understand you might want to keep unpublished data private, but you should have something published that can be used to run the benchmarks on.

I would suggest at least clearly documenting the benchmarks that only make sense to run on large datasets that may not be available as part of the package, and providing data for the benchmarks where you can get meaningful results within the limits of what you can store on GitHub.

**Comment by henry2004y** [comment]
Thanks for the suggestions! Upon inquiring our colleagues, we now find some open-access Vlasiator data. We will update the benchmarks and add the links to the data.

**Comment by henry2004y** [comment]
In Vlasiator.jl v0.9.34, we have updated `perf.jl`, `perf.py` as well as the benchmark results. `perf.jl` and `perf.py` can be run directly to produce a major portion of the benchmarks listed in the doc. One of the files (file index 5) is private, while others are all publicly accessible. We have also fixed some issues in comparing the performance between Python/Numpy and Julia, which should now give fairer results.

**Comment by tkoskela** [comment]
I would still like to ask for a bit clearer documentation on Benchmarks. With some guesswork I can link some of the numbers reported in https://henry2004y.github.io/Vlasiator.jl/dev/benchmark/ to the output of `benchmarkpkg(Vlasiator)`, for example file index 2 of "loading meta data" is probably `"meta" => Trial(310.480 μs)`. If you could describe on the Benchmarks page which numbers I can expect to extract from running benchmarkpkg on the data you provide, and how, that would make me happy.

**Comment by tkoskela** [comment]
I would also note that I ran into an error 
```
ERROR: LoadError: Cannot locate '(Julia)Artifacts.toml' file when attempting to use artifact 'testdata' in 'Main'
```
that seems to be reported in https://github.com/JuliaLang/IJulia.jl/issues/1060. The solution in the first comment of the issue fixed it for me

**Comment by henry2004y** [comment]
I ran this issue as well and indeed the first comment fixed it. However, for some reason it didn't work for the pkgbenchmark that I added recently. In CI, my current workaround is to manually create a symbolic link under the benchmark folder:
https://github.com/henry2004y/Vlasiator.jl/blob/19b203b46d9d602c9463057652a8c21756082169/.github/workflows/benchmark.yml#L26

Then this works for both CI and local pkgbenchmark.

**Comment by henry2004y** [comment]
> I would still like to ask for a bit clearer documentation on Benchmarks. With some guesswork I can link some of the numbers reported in https://henry2004y.github.io/Vlasiator.jl/dev/benchmark/ to the output of `benchmarkpkg(Vlasiator)`, for example file index 2 of "loading meta data" is probably `"meta" => Trial(310.480 μs)`. If you could describe on the Benchmarks page which numbers I can expect to extract from running `benchmarkpkg` on the data you provide, and how, that would make me happy.

Are you running [`perf.jl`](https://github.com/henry2004y/Vlasiator.jl/blob/master/benchmark/perf.jl) or [`benchmarks.jl`](https://github.com/henry2004y/Vlasiator.jl/blob/master/benchmark/benchmarks.jl) @tkoskela ? In the benchmark page, the numbers are generated with perf.jl and perf.py, while benchmarks.jl is used for checking regressions within the pkg. I can cleanup the benchmarks further to get better links to each part.

**Comment by tkoskela** [comment]
I was running `benchmarks.jl`, thank you for pointing that out! I can verify the benchmark data, so I am happy to close the issue. Labeling the benchmark suites in `perf.jl` to match the documentation a bit better could be helpful.

**Comment by henry2004y** [comment]
Yeah this is indeed kind of confusing, because currently PkgBenchmarks requires the file benchmarks.jl so I cannot use it for comparing against Python with exactly the same tasks and larger datasets. But we will find a clearer (and automatic) way of doing this!
